import React from 'react';

import {
  Apple,
  Bus,
  Dumbbell,
  Utensils,
  ShoppingBag,
  Wallet,
  Coffee,
  Gamepad2,
  Car,
  Plane,
  Train,
  Heart,
  DollarSign,
  CreditCard,
  Banknote,
  PiggyBank,
  Gift,
  Music,
  Film,
  Tv,
  Headphones,
  Book,
  PenTool,
  Home,
  Store,
  User,
  Settings,
  Bell,
  Calendar,
  Clock,
} from 'lucide-react';

export const EXPENSE_ICONS = {
  Utensils: <Utensils size={30} />,
  Bus: <Bus size={30} />,
  Apple: <Apple size={30} />,
  Dumbbell: <Dumbbell size={30} />,
  ShoppingBag: <ShoppingBag size={30} />,
  Wallet: <Wallet size={30} />,
  Coffee: <Coffee size={30} />,
  Gamepad: <Gamepad2 size={30} />,
  Car: <Car size={30} />,
  Plane: <Plane size={30} />,
  Train: <Train size={30} />,
  Heart: <Heart size={30} />,
  DollarSign: <DollarSign size={30} />,
  CreditCard: <CreditCard size={30} />,
  Banknote: <Banknote size={30} />,
  PiggyBank: <PiggyBank size={30} />,
  Gift: <Gift size={30} />,
  Music: <Music size={30} />,
  Film: <Film size={30} />,
  Tv: <Tv size={30} />,
  Headphones: <Headphones size={30} />,
  Book: <Book size={30} />,
  PenTool: <PenTool size={30} />,
  Home: <Home size={30} />,
  Store: <Store size={30} />,
  User: <User size={30} />,
  Settings: <Settings size={30} />,
  Bell: <Bell size={30} />,
  Calendar: <Calendar size={30} />,
  Clock: <Clock size={30} />,
};

export const COLORS = {
  red: '#ef4444',
  blue: '#3b82f6',
  green: '#22c55e',
  yellow: '#eab308',
  purple: '#a855f7',
  orange: '#f97316',
  teal: '#14b8a6',
  pink: '#ec4899',
};

export const CATEGORIES = [
  { name: 'Food', type: 'Expenses', icon: 'Utensils', color: COLORS.red },
  { name: 'Transport', type: 'Expenses', icon: 'Bus', color: COLORS.blue },
  { name: 'Groceries', type: 'Expenses', icon: 'Apple', color: COLORS.green },
  { name: 'Sport', type: 'Expenses', icon: 'Dumbbell', color: COLORS.orange },
  {
    name: 'Shopping',
    type: 'Expenses',
    icon: 'ShoppingBag',
    color: COLORS.purple,
  },
  { name: 'Bills', type: 'Expenses', icon: 'Wallet', color: COLORS.yellow },
  { name: 'Cafe', type: 'Expenses', icon: 'Coffee', color: COLORS.teal },
  {
    name: 'Entertainment',
    type: 'Expenses',
    icon: 'Gamepad',
    color: COLORS.pink,
  },
];
